left_storage:
  frame_id: "base_link"
  position: [0.0, 0.55, 0.34]
  range_x: [-0.124, 0.117]
  range_y: [0.381, 0.717]
  release_z: 0.34
  release_z_from_grasp: true
  storage_base_z: 0.06
  object_clearance_z: 0.15
  use_grasp_orientation: true
  approach_z: 0.15
  retreat_z: 0.20
  approach_duration: 2.8
  release_duration: 2.0
  open_timeout: 2.5
  post_release_sleep: 0.8
  retreat_duration: 3.0
  return_home_after_place: true
  return_home_duration: 4.0

right_storage:
  frame_id: "base_link"
  position: [0.0, -0.55, 0.34]
  range_x: [-0.124, 0.117]
  range_y: [-0.717, -0.381]
  release_z: 0.34
  release_z_from_grasp: true
  storage_base_z: 0.06
  object_clearance_z: 0.15
  use_grasp_orientation: true
  approach_z: 0.15
  retreat_z: 0.20
  approach_duration: 2.8
  release_duration: 2.0
  open_timeout: 2.5
  post_release_sleep: 0.8
  retreat_duration: 3.0
  return_home_after_place: true
  return_home_duration: 4.0

shelf:
  frame_id: "base_link"
  position: [0.86, -0.30, 0.50]
  x: 0.86
  y_slots: [-0.30]
  release_z: 0.50
  approach_x_offset: -0.16
  retreat_x_offset: -0.28
  retreat_lift_z: 0.02
  approach_duration: 2.8
  release_duration: 2.0
  open_timeout: 2.5
  post_release_sleep: 0.8
  retreat_duration: 3.0
  return_home_after_place: true
  return_home_duration: 4.0
